[package]
name = "chapter2"
version = "0.1.0"
edition = "2021"
default-run = "chapter2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"
generic_search = "0.1.0"

[patch.crates-io]
generic_search = { path = "./generic_search" }

