[package]
name = "chapter4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic_search = "0.1.0"

[patch.crates-io]
generic_search = { path = "../chapter2/generic_search" }
