[package]
name = "chapter5"
default-run = "chapter5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libflate = "2.1.0"
rand = "0.9.2"
