[package]
name = "chapter1"
version = "0.1.0"
edition = "2021"
default-run = "chapter1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.5.1"
rand = "0.9.2"
